#spring:
#  application:
#    name: API-GATEWAY
#  profiles:
#    active: local
#
#server:
#  port: 8085

server:
  port: 8085

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: BMS-SERVICE
          uri: lb://BMS-SERVICE
          predicates:
            - Path=/cities/**,/actors/**,/theatres/**,/bookings/**,/movies/**,/shows/**, /users/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/user/**,/otp/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.netflix.eureka: TRACE
